nombre = str(input("Ingrese su nombre:"))
print("Su nombre es",nombre)
Apellido = str(input("Ingrese su primer apellido:"))
print("Su primer apellido es",Apellido)
Apellido2 = str(input("Ingrese su segundo apellido:"))
print("Su segundo apellido es",Apellido2)
Edad = int(input("Ingrese su edad:"))
print("Tu edad es",Edad)
Estatura = float(input("Ingrese su estatura:"))
print("Tu estatura es:",Estatura)
Sisben = int(input("Ingrese su nivel de sisben:"))
print("Tu nivel de sisben es:",Sisben)
Peso = float(input("Ingrese su peso:"))
print("Tu peso es:",Peso)
Color_de_piel = str(input("Ingrese su color de piel:"))
print("Su color de piel es:",Color_de_piel)
Nacionalidad = str(input("Ingrese su nacionalidad:"))
print("Su nacionalidad es:",Nacionalidad)
Idioma_nativo = str(input("Ingrese su idioma nativo:"))
print("Tu idioma nativo es:",Idioma_nativo)
Idioma2 = str(input("Ingrese que otro idioma maneja:"))
print("Sus otros idiomas son:",Idioma2)
Educacion = str(input("Que nivel de educacion tiene:"))
print("Su nivel de educacion es:",Educacion)
Hermanos = int(input("Cuantos hermanos tiene:"))
print("Usted tiene:",Hermanos, "hermanos")
Hermanas = int(input("Cuantas hermanas tiene:"))
print("Usted tiene:",Hermanas, "hermanas")
Equipo = str(input("Que equipo de futbol te gusta:"))
print("El equipo que te gusta es:",Equipo)
vivienda = int(input("Con cuantas personas vive:"))
print("Usted vive con:",vivienda)
icfes = int(input("Cuanto puntaje saco en el icfes:"))
print("Tu puntaje en le icfes es de:",icfes)
colegio = str(input("Nombre de la institucion donde estudio:"))
print("Estudiaste en la:",colegio)
estudio_futuro = str(input("Que le gustaria estudiar:"))
print("Su carrera a estudiar seria:",estudio_futuro)
Numero_cel = int(input("Ingrese su numero de contacto:"))
print("Su numero de contacto es:",Numero_cel)

print("Muchas gracias por poner sus datos C:")